clean:
  classification: false
  combine_files: false
  correlation_metric: pearson
  input_max_correlation_threshold: 1.0
  onehot_encode_target: false
  percentage_zeros_threshold: 1.0
  target: tool_wear
evaluate:
  show_inputs: false
featurize:
  add_gradient: null
  add_maximum: null
  add_mean: null
  add_min_max_range: null
  add_minimum: null
  add_peak_frequency: null
  add_slope: null
  add_slope_cos: null
  add_slope_sin: null
  add_standard_deviation: null
  add_sum: null
  add_variance: null
  remove_features: null
  rolling_window_size_max_min: 10
  rolling_window_size_mean: 10
  rolling_window_size_standard_deviation: 10
  rolling_window_size_sum: 10
  row_abs_diff: null
  target_min_correlation_threshold: 0.0
  use_all_engineered_features_on_all_variables: false
  variables_to_include: null
profile:
  continual: true
  dataset: broaching_toolwear_5X
scale:
  input: minmax
  output: null
sequentialize:
  future_predict: false
  overlap: 0
  shuffle_samples: false
  target_size: 1
  window_size: 25
split:
  calibrate_split: 0.0
  shuffle_files: false
  train_split: 0.5
train:
  activation_function: relu
  batch_size: 256
  dropout: 0.1
  early_stopping: false
  hyperparameter_tuning: false
  kernel_size: 5
  learning_method: xgboost
  maxpooling: false
  maxpooling_size: 4
  n_epochs: 100
  n_flattened_layers: 2
  n_flattened_nodes: 16
  n_layers: 2
  n_neurons: 100
  patience: 20
  seed: 2020
  unit_type: LSTM
