profile:
    dataset: broaching_with_tool_wear
    continual: True

clean:
    target: tool_wear
    classification: False
    onehot_encode_target: False
    combine_files: True
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        - acc1_x
        - acc1_y
        - acc1_z
        - acc2_x
        - acc2_y
        - acc2_z

    # Row based engineered features
    # Features listed must be included above (if not empty), but can be removed after if desired under remove_features
    row_abs_diff:
    # - [variable1, variable2]

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: True

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - variable1
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    # rolling_window_size_sum: 128000
    # rolling_window_size_mean: 128000
    # rolling_window_size_max_min: 128000
    # rolling_window_size_standard_deviation: 128000
    rolling_window_size_sum: 128000
    rolling_window_size_mean: 128000
    rolling_window_size_max_min: 128000
    rolling_window_size_standard_deviation: 128000

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        # - "Unnamed: 0"
        # - variable1
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.6
    shuffle_files: True
    calibrate_split: 0.0

scale:
    input: minmax
    output:

sequentialize:
    window_size: 1
    # window_size: 12800
    overlap: 0
    target_size: 1
    shuffle_samples: True
    future_predict: False

train:
    seed: 2022
    learning_method: rnn
    hyperparameter_tuning: False

    # Parameters for deep learning (dnn, cnn, rnn):
    n_epochs: 100
    early_stopping: False
    patience: 100
    activation_function: relu
    batch_size: 256
    n_layers: 2
    n_neurons: 32
    dropout: 0.1

    # Parameters for cnn and rnn
    n_flattened_layers: 2
    n_flattened_nodes: 32

    # Parameters for cnn:
    kernel_size: 10
    maxpooling: True
    maxpooling_size: 4

    # Parameters for rnn:
    unit_type: LSTM

evaluate:
    show_inputs: False
