profile:
    dataset: piston_rod
    # dataset: broaching_with_tool_wear
    # dataset: cnc_milling_with_toolwear
    # dataset: bhp_fitbit
    continual: True

clean:
    target: time_until_tool_change
    # target: tool_wear
    # target: X1_ActualPosition
    # target: fas
    classification: False
    onehot_encode_target: False
    combine_files: False
    percentage_zeros_threshold: 1.0
    correlation_metric: pearson
    input_max_correlation_threshold: 1.0

featurize:
    # If empty, all input variables are used
    variables_to_include:
        - NCLine
        # - ProgramName
        - ProgramStatus
        - SpindleRPM
        - aaCurr1
        - aaCurr13
        - aaCurr14
        - aaCurr16
        - aaCurr2
        - aaCurr3
        - aaCurr4
        - aaCurr5
        - aaCurr6
        - aaCurr7
        - aaCurr8
        - aaCurr9
        - aaLoad1
        - aaLoad13
        - aaLoad14
        - aaLoad16
        - aaLoad2
        - aaLoad3
        - aaLoad4
        - aaLoad5
        - aaLoad6
        - aaLoad7
        - aaLoad8
        - aaLoad9
        - aaPower1
        - aaPower13
        - aaPower14
        - aaPower16
        - aaPower2
        # - aaPower20
        - aaPower3
        - aaPower4
        - aaPower5
        - aaPower6
        - aaPower7
        - aaPower8
        - aaPower9
        - aaTorque1
        - aaTorque13
        - aaTorque14
        - aaTorque16
        - aaTorque2
        - aaTorque3
        - aaTorque4
        - aaTorque5
        - aaTorque6
        - aaTorque7
        - aaTorque8
        - aaTorque9
        - actFeedRate1
        - actFeedRate13
        - actFeedRate14
        - actFeedRate16
        - actFeedRate2
        - actFeedRate3
        - actFeedRate5
        - actFeedRate6
        - actFeedRate7
        - actFeedRate8
        - actFeedRate9
        - actSpeed1
        - actSpeed2
        - actSpeed3
        - actToolBasePos1
        - actToolBasePos3
        - measPos11
        - measPos113
        - measPos114
        - measPos116
        - measPos12
        - measPos13
        - measPos15
        - measPos16
        - measPos17
        - measPos18
        - measPos19
        - measPos213
        - measPos214
        - measPos216
        - measPos22
        - measPos23
        - measPos25
        - measPos28
        - measPos29
        # - NCLine
        # - measPos116
        # - measPos113
        # - actFeedRate14
        # - SpindleRPM
        # - actFeedRate1
        # - acc1_x
        # - acc1_y
        # - acc1_z
        # - acc2_x
        # - acc2_y
        # - acc2_z
      # - age
      # - heart_rate_bpm_min
      # - bmi
      # - resting_heart_rate
      # - heart_rate_bpm_mean
      # - levels.summary.light.minutes
      # - weight
      # - sedentary_minutes
      # # Negative correlation:
      # - gender
      # - height
      # - very_active_minutes

    # By setting this to True, the add_-options below are overrided.
    use_all_engineered_features_on_all_variables: False

    row_abs_diff:
        # - [variable1, variable2]

    # List the variables below each add_* to add engineered feature
    add_sum:
        # - variable1
    add_gradient:
        # - variable1
    add_mean:
        # - variable1
    add_maximum:
        # - variable1
    add_minimum:
        # - variable1
    add_min_max_range:
        # - variable1
    add_slope:
        # - variable1
    add_slope_sin:
        # - variable1
    add_slope_cos:
        # - variable1
    add_standard_deviation:
        # - variable1
    add_variance:
        # - variable1
    add_peak_frequency:
        # - variable1
    rolling_window_size_sum: 100
    rolling_window_size_mean: 100
    rolling_window_size_max_min: 100
    rolling_window_size_standard_deviation: 100

    # List features here to remove the raw variables after engineering features
    # from them
    remove_features:
        - timestamp
        - TimeSinceStartup
        - machining_timesteps
        # - variable1
    target_min_correlation_threshold: 0.0

split:
    train_split: 0.7
    calibrate_split: 0.0
    shuffle_files: True
    shuffle_samples_before_split: False

scale:
    input: minmax
    output:

sequentialize:
    window_size: 10
    overlap: 0
    target_size: 1
    shuffle_samples: True
    future_predict: False

train:
    seed: 2020
    learning_method: xgboost
    #ensemble: False
    hyperparameter_tuning: False

    # Parameters for deep learning (dnn, cnn, lstm etc):
    n_epochs: 1000
    early_stopping: False
    patience: 100
    activation_function: relu
    batch_size: 256
    # n_layers: 5
    # n_neurons: [256,128,128,64,64]
    n_layers: 4
    n_neurons: 32
    dropout: 0.1

    # Parameters for cnn and rnn
    n_flattened_layers: 2
    n_flattened_nodes: 64

    # Parameters for cnn:
    kernel_size: 3
    maxpooling: False
    maxpooling_size: 4

    # Parameters for rnn:
    unit_type: LSTM

evaluate:
    performance_metric: auto
    threshold_for_ensemble_models: auto
    show_inputs: False

#explain: 
    #number_of_background_samples: 5
    #number_of_summary_samples: 5
    #seed: 2020
